/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedInsightsRouteImport } from './routes/_authenticated/insights'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedExpensesRouteImport } from './routes/_authenticated/expenses'
import { Route as AuthenticatedAddRouteImport } from './routes/_authenticated/add'
import { Route as AuthenticatedExpensesCategoryRouteImport } from './routes/_authenticated/expenses.$category'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedInsightsRoute = AuthenticatedInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExpensesRoute = AuthenticatedExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAddRoute = AuthenticatedAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExpensesCategoryRoute =
  AuthenticatedExpensesCategoryRouteImport.update({
    id: '/$category',
    path: '/$category',
    getParentRoute: () => AuthenticatedExpensesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/add': typeof AuthenticatedAddRoute
  '/expenses': typeof AuthenticatedExpensesRouteWithChildren
  '/home': typeof AuthenticatedHomeRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/expenses/$category': typeof AuthenticatedExpensesCategoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/add': typeof AuthenticatedAddRoute
  '/expenses': typeof AuthenticatedExpensesRouteWithChildren
  '/home': typeof AuthenticatedHomeRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/expenses/$category': typeof AuthenticatedExpensesCategoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/add': typeof AuthenticatedAddRoute
  '/_authenticated/expenses': typeof AuthenticatedExpensesRouteWithChildren
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/insights': typeof AuthenticatedInsightsRoute
  '/_authenticated/expenses/$category': typeof AuthenticatedExpensesCategoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/add'
    | '/expenses'
    | '/home'
    | '/insights'
    | '/expenses/$category'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/add'
    | '/expenses'
    | '/home'
    | '/insights'
    | '/expenses/$category'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/add'
    | '/_authenticated/expenses'
    | '/_authenticated/home'
    | '/_authenticated/insights'
    | '/_authenticated/expenses/$category'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/insights': {
      id: '/_authenticated/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AuthenticatedInsightsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/expenses': {
      id: '/_authenticated/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AuthenticatedExpensesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/add': {
      id: '/_authenticated/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AuthenticatedAddRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/expenses/$category': {
      id: '/_authenticated/expenses/$category'
      path: '/$category'
      fullPath: '/expenses/$category'
      preLoaderRoute: typeof AuthenticatedExpensesCategoryRouteImport
      parentRoute: typeof AuthenticatedExpensesRoute
    }
  }
}

interface AuthenticatedExpensesRouteChildren {
  AuthenticatedExpensesCategoryRoute: typeof AuthenticatedExpensesCategoryRoute
}

const AuthenticatedExpensesRouteChildren: AuthenticatedExpensesRouteChildren = {
  AuthenticatedExpensesCategoryRoute: AuthenticatedExpensesCategoryRoute,
}

const AuthenticatedExpensesRouteWithChildren =
  AuthenticatedExpensesRoute._addFileChildren(
    AuthenticatedExpensesRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAddRoute: typeof AuthenticatedAddRoute
  AuthenticatedExpensesRoute: typeof AuthenticatedExpensesRouteWithChildren
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedInsightsRoute: typeof AuthenticatedInsightsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAddRoute: AuthenticatedAddRoute,
  AuthenticatedExpensesRoute: AuthenticatedExpensesRouteWithChildren,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedInsightsRoute: AuthenticatedInsightsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
